spring:
	profile:
		active:
			- dev
---

spring:
	profile: dev  #开发环境
	application:
		name: microservicecloud-config-ittx-dev
--- 
spring:
	profile: test  #测试环境
	application:
		name: microservicecloud-config-ittx-test

# 请务必以UTF-8的格式保存