


spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-ittx-dev

---
spring:
  profiles: test
      application:
        name: microservicecloud-config-ittx-test